# Generated by Django 4.2.5 on 2023-10-05 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cookbook", "0002_initial"),
        ("ingredient", "0001_initial"),
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cookbook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="cookbook.cookbook",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="favorite_by",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(to="ingredient.ingredient"),
        ),
    ]
