# Generated by Django 4.2.5 on 2023-10-05 22:03

from django.db import migrations, models
import registration_profile.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistrationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=registration_profile.models.code_generator, max_length=5
                    ),
                ),
                ("used", models.BooleanField(default=False)),
            ],
        ),
    ]
